---
extends: airbnb-base
env:
  browser: true
  jquery: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  quotes:
    - 2
    - single
  no-unused-vars: 0
  no-console: 0
  indent: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
  import/no-webpack-loader-syntax: 0
  import/first: 0
  import/extensions: 0
  prefer-template: 0
  max-len: 0
  object-shorthand: 0
  arrow-body-style: 0
  no-useless-concat: 0
  no-param-reassign: 0
  consistent-return: 0
  newline-per-chained-call: 0
  prefer-rest-params: 0
  no-new: 0
  no-confusing-arrow: 0
  global-require: 0
  comma-dangle: 0
  class-methods-use-this: 0
  dot-location: 0
  arrow-parens: 0
  no-plusplus: 0
  prefer-spread: 0
